"CIRCLE_tb.vvp": CIRCLE_tb.v CIRCLE.v CPU.v ALU.v CTRL.v DATAMEM.v IMMGEN.v INSMEM.v MUXREG.v MUXRS.v NPC.v opcode_def.v PC.v REGFILE.v
	iverilog -o "CIRCLE_tb.vvp" CIRCLE_tb.v CIRCLE.v CPU.v ALU.v CTRL.v DATAMEM.v IMMGEN.v INSMEM.v MUXREG.v MUXRS.v NPC.v opcode_def.v PC.v REGFILE.v
	vvp CIRCLE_tb.vvp